baseURL = 'https://hugoblogapp.com'
languageCode = 'en-us'
title = 'Muyinda Brian Blog'

paginate = 4

[params]
  description = "Web Developer| Web Developer Uganda | Web Designer| Mobile App Developer Uganda"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"